/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.0.27
 * Generated at: 2022-12-22 01:30:58 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.DB;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.sql.*;

public final class Headquarter_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("body {\r\n");
      out.write("    font-family: 'Noto Sans KR', sans-serif;\r\n");
      out.write("    display: flex;\r\n");
      out.write("    justify-content: center;\r\n");
      out.write("    height: 95vh;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"EUC-KR\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>");


Class.forName("org.mariadb.jdbc.Driver");
String jdbcDriver = "jdbc:mariadb://localhost:3306/homework";
String dbUser = "root";
String dbPass = "22489612up!";


Connection conn = null;
Statement stmt = null;
ResultSet result = null;

try {
	conn = DriverManager.getConnection(jdbcDriver, dbUser, dbPass);
	stmt = conn.createStatement();
	String query = "SELECT * FROM headquarter";
	result = stmt.executeQuery(query);
	int check=1;
	if(request.getParameter("checkcheck") == null) {
		
	} else {
	check = Integer.parseInt(request.getParameter("checkcheck"));
	}

      out.write("\r\n");
      out.write("\r\n");
      out.write("<body style=\"background-color: #edf2f9 !important;\">\r\n");
      out.write("    <div>\r\n");
      out.write("        <h1>Headquarter</h1>\r\n");
      out.write("        <h4>\r\n");
      out.write("				show your Headquarter\r\n");
      out.write("        </h4>\r\n");
      out.write("        <div>\r\n");
      out.write("                <table border = \"1\">\r\n");
      out.write("                    <thead>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                        <td>ID</td>\r\n");
      out.write("                        <td>Name</td>\r\n");
      out.write("                        <td>Planet</td>\r\n");
      out.write("                        <td>Continent</td>\r\n");
      out.write("                        <td>ManagerName</td>\r\n");
      out.write("                        <td>Budget</td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                    </thead>\r\n");
      out.write("                    ");

                    while(result.next()) {
                    	if(check==1){
                    
      out.write("\r\n");
      out.write("                    <tbody>\r\n");
      out.write("                        <tr onclick=\"trClick(this)\">\r\n");
      out.write("                        	<td>");
      out.print(result.getInt("ID"));
      out.write("</td>\r\n");
      out.write("                            <td>");
      out.print(result.getString("Name"));
      out.write("</td>\r\n");
      out.write("                            <td>");
      out.print(result.getString("Planet"));
      out.write("</td>\r\n");
      out.write("                            <td>");
      out.print(result.getString("Continent"));
      out.write("</td>\r\n");
      out.write("                            <td>");
      out.print(result.getString("ManagerName"));
      out.write("</td>\r\n");
      out.write("                            <td>");
      out.print(result.getInt("Budget") );
      out.write("</td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                   \r\n");
      out.write("                    </tbody>\r\n");
      out.write("                    ");
} else if(check==2) {

                    	String search = request.getParameter("search");
                		String Text = result.getString("planet");
                		if(search.equals(Text)){

                    	
      out.write("\r\n");
      out.write("                        <tbody>\r\n");
      out.write("                            <tr onclick=\"trClick(this)\">\r\n");
      out.write("                            	<td>");
      out.print(result.getInt("ID"));
      out.write("</td>\r\n");
      out.write("                                <td>");
      out.print(result.getString("Name"));
      out.write("</td>\r\n");
      out.write("                                <td>");
      out.print(result.getString("Planet"));
      out.write("</td>\r\n");
      out.write("                                <td>");
      out.print(result.getString("Continent"));
      out.write("</td>\r\n");
      out.write("                                <td>");
      out.print(result.getString("ManagerName"));
      out.write("</td>\r\n");
      out.write("                                <td>");
      out.print(result.getInt("Budget") );
      out.write("</td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                       \r\n");
      out.write("                        </tbody>\r\n");
      out.write("                        ");

                    }
                    }
                    	} 
      out.write("\r\n");
      out.write("                </table>\r\n");
      out.write("        </div>\r\n");
      out.write("        <form id=\"Head_insert\" action =\"./manage/Head_manage.jsp\" method=\"get\">\r\n");
      out.write("        <h4>Insert</h4>\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("        <input id=\"Name1\" name=\"Name1\" type=\"text\" placeHolder=\"Name\">\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("      <select name=\"Planet1\">\r\n");
      out.write("        <option>Mars</option>\r\n");
      out.write("        <option>Earth</option>\r\n");
      out.write("        <option>Mercury</option>\r\n");
      out.write("        <option>Venus</option>\r\n");
      out.write("        <option>Saturn</option>\r\n");
      out.write("      </select>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("        \r\n");
      out.write("      <select name=\"Continent1\">\r\n");
      out.write("        <option>Asia</option>\r\n");
      out.write("        <option>Africa</option>\r\n");
      out.write("        <option>America</option>\r\n");
      out.write("        <option>Europe</option>\r\n");
      out.write("        <option>Oceania</option>\r\n");
      out.write("      </select>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("        <input id=\"ManagerName1\" name=\"ManagerName1\" type=\"text\" placeHolder=\"ManagerName\">\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("        <input id=\"Budget1\" name=\"Budget1\" type=\"text\" placeHolder=\"Budget\">\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"hd_insert_button\">\r\n");
      out.write("        <button id=\"insert_button1\" type = \"submit\" style=\"background-color: #4c59fd\">insert</button>\r\n");
      out.write("        </div>\r\n");
      out.write("        <input name=\"manage_num\" type=\"hidden\" value=\"1\">\r\n");
      out.write("        </form>\r\n");
      out.write("        \r\n");
      out.write("        <form id=\"Head_update\" action=\"./manage/Head_manage.jsp\" method=\"get\">\r\n");
      out.write("         <h4>Update</h4>\r\n");
      out.write("        <p>update할 아이디를 입력하세요!</p>\r\n");
      out.write("       <div class=\"row\">\r\n");
      out.write("        <input id=\"head_id\" name=\"headupdate_id\" type=\"text\" placeHolder=\"id\">\r\n");
      out.write("        </div>\r\n");
      out.write("       <div class=\"row\">\r\n");
      out.write("      <select name=\"select\">\r\n");
      out.write("        <option>Name</option>\r\n");
      out.write("        <option>Planet</option>\r\n");
      out.write("        <option>Continent</option>\r\n");
      out.write("        <option>ManagerName</option>\r\n");
      out.write("        <option>Budget</option>\r\n");
      out.write("      </select>\r\n");
      out.write("        </div>\r\n");
      out.write("       <div class=\"row\">\r\n");
      out.write("        <input id=\"head_id\" name=\"update\" type=\"text\" placeHolder=\"수정값\">\r\n");
      out.write("        </div>\r\n");
      out.write("        <div>\r\n");
      out.write("        <button id=\"update_button1\" type = \"submit\" style=\"background-color: #4c59fd\">update</button>\r\n");
      out.write("        </div>\r\n");
      out.write("        <input name=\"manage_num\" type=\"hidden\" value=\"2\">\r\n");
      out.write("        </form>\r\n");
      out.write("        \r\n");
      out.write("        <form id=\"Head_delete\" action=\"./manage/Head_manage.jsp\" method=\"get\">\r\n");
      out.write("        <h4>Delete</h4>\r\n");
      out.write("        <p>delete할 아이디를 입력하세요!</p>\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("        <input id=\"head_id\" name=\"headdelete_id\" type=\"text\" placeHolder=\"id\">\r\n");
      out.write("        </div>\r\n");
      out.write("        <div>\r\n");
      out.write("        <button id=\"delete_button1\" type = \"submit\" style=\"background-color: #4c59fd\">delete</button>\r\n");
      out.write("        </div>\r\n");
      out.write("        <input name=\"manage_num\" type=\"hidden\" value=\"3\">\r\n");
      out.write("        </form>\r\n");
      out.write("        \r\n");
      out.write("        <form action=\"../Sys_admin.jsp\" method=\"get\">\r\n");
      out.write("        <h4>목록으로 이동하기!</h4>\r\n");
      out.write("        <div>\r\n");
      out.write("        <button>목록</button>\r\n");
      out.write("        </div>\r\n");
      out.write("        <br><br><br><br><br><br><br><br>\r\n");
      out.write("        </form>\r\n");
      out.write("    </div>\r\n");

	result.close();
	stmt.close();
	conn.close();
} catch(SQLException e) {
	response.sendRedirect("Headquarter.jsp");
	out.println("err."+e.toString());
}
	
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
