/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.0.27
 * Generated at: 2022-12-21 22:19:58 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.sql.*;

public final class booktrain_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"EUC-KR\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("tbody td:hover {\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css\" rel=\"stylesheet\"\r\n");
      out.write("        integrity=\"sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC\" crossorigin=\"anonymous\">\r\n");
      out.write("\r\n");
      out.write("<body style=\"width:90%;\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<h1> Welcome train!</h1>\r\n");
      out.write("<p> 운항중인 열차편에 대한 예약 기능 </p>\r\n");

Class.forName("org.mariadb.jdbc.Driver");
String jdbcDriver = "jdbc:mariadb://localhost:3306/homework";
String dbUser = "root";
String dbPass = "22489612up!";
String query = " select * from operation,TrainCode where operation.TrainCode_ID=TrainCode.ID order by operation.id;";

Connection conn = null;
Statement stmt = null;
ResultSet result = null;


try {
	conn = DriverManager.getConnection(jdbcDriver, dbUser, dbPass);
	stmt = conn.createStatement();
	result = stmt.executeQuery(query);
	int check = Integer.parseInt(request.getParameter("indexNum"));

      out.write("  <table class=\"boardTable table table-hover\" border = \"1\">\r\n");
      out.write("                    <thead class=\"table-primary\">\r\n");
      out.write("                        <tr>\r\n");
      out.write("                        <td>ID</td>\r\n");
      out.write("                        <td>DeptStatus</td>\r\n");
      out.write("                        <td>ArvStatus</td>\r\n");
      out.write("                        <td>Day</td>\r\n");
      out.write("                        <td>StartStation</td>\r\n");
      out.write("                        <td>StartTime</td>\r\n");
      out.write("                        <td>EndStation</td>\r\n");
      out.write("                        <td>EndTime</td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                    </thead>\r\n");
      out.write("                    ");

                    while(result.next()) {
                		if(check == result.getInt("ID")){
                    
      out.write("\r\n");
      out.write("                    <tbody id=\"tablebody\" class=\"table-light\">\r\n");
      out.write("                        <tr onclick=\"trClick(this)\">\r\n");
      out.write("                        	<td>");
      out.print(result.getInt("ID"));
      out.write("</td>\r\n");
      out.write("                            <td>");
      out.print(result.getString("DeptStatus"));
      out.write("</td>\r\n");
      out.write("                            <td>");
      out.print(result.getString("ArvStatus"));
      out.write("</td>\r\n");
      out.write("                            <td>");
      out.print(result.getString("Day"));
      out.write("</td>\r\n");
      out.write("                            <td>");
      out.print(result.getString("StartStation"));
      out.write("</td>\r\n");
      out.write("                            <td>");
      out.print(result.getString("StartTime") );
      out.write("</td>\r\n");
      out.write("                            <td>");
      out.print(result.getString("EndStation") );
      out.write("</td>\r\n");
      out.write("                            <td>");
      out.print(result.getString("EndTime") );
      out.write("</td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                   \r\n");
      out.write("                    </tbody>\r\n");
      out.write("                    ");
}} 
      out.write("\r\n");
      out.write("                </table>\r\n");
      out.write("                <form method=\"get\" action=\"Login.jsp\">\r\n");
      out.write("     		 <p>정말 예약하시겠습니까??</p>\r\n");
      out.write("     		 <label><input type=\"radio\" name=\"aaaa\" value=\"1\"> yes</label>\r\n");
      out.write("     		 <label><input type=\"radio\" name=\"aaaa\" value=\"0\"> No</label>\r\n");
      out.write("     		 <p><input type=\"submit\" value=\"Submit\"> <input type=\"reset\" value=\"Reset\"></p>\r\n");
      out.write("   			 </form>\r\n");
      out.write("                \r\n");
      out.write("                \r\n");
      out.write("                ");

	result.close();
	stmt.close();
	conn.close();
} catch(SQLException e) {
	out.println("err."+e.toString());
}

      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
