/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.0.27
 * Generated at: 2022-12-23 10:11:32 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.sql.*;

public final class login_005fengineer_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<style>\r\n");
      out.write("body {\r\n");
      out.write("    font-family: 'Noto Sans KR', sans-serif;\r\n");
      out.write("    display: flex;\r\n");
      out.write("    justify-content: center;\r\n");
      out.write("    height: 95vh;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"EUC-KR\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>");


Class.forName("org.mariadb.jdbc.Driver");
String jdbcDriver = "jdbc:mariadb://localhost:3306/homework";
String dbUser = "root";
String dbPass = "22489612up!";


Connection conn = null;
Statement stmt = null;
ResultSet result = null;
try {
	conn = DriverManager.getConnection(jdbcDriver, dbUser, dbPass);
	stmt = conn.createStatement();
	String query = "SELECT * FROM operation";
	result = stmt.executeQuery(query);
	String user_name = (String) session.getAttribute("user_name");
	String Engineer_ID = (String) session.getAttribute("Engineer_ID");
	int Engin = Integer.parseInt(Engineer_ID);

	String query2 = "select A.DeptStatus, A.ArvStatus , B.StartStation, B.StartTime, B.EndStation, B.EndTime, C.Type, C.Conditions from (select * from operation where Engineer_ID="+ Engin +") as A, Traincode B, train C where A.Traincode_ID=B.ID AND A.Train_ID = C.ID;";


      out.write("\r\n");
      out.write("\r\n");
      out.write("<body style=\"background-color: #edf2f9 !important;\">\r\n");
      out.write("    <div><p>operation 자신과 관련된 데이터만 관리함. 섹션에서 유저 아이디 받아와서 자신 데이터만 관리 \r\n");
      out.write("      운행 기록 생성 업데이트 삭제 + 모든 운행 한눈에 보기 기능(바로 그냥 띄어줌 )</p>\r\n");
      out.write("        <h1 class=\"title\">");
      out.print(user_name);
      out.write(" 기관사님 반갑습니다.</h1><p>기관사님의 코드번호는 ");
      out.print(Engineer_ID);
      out.write("입니다.</p>\r\n");
      out.write("        <h4 class=\"titleScript\">\r\n");
      out.write("				운행관리\r\n");
      out.write("        </h4>\r\n");
      out.write("        <div style=\"float:left;\">\r\n");
      out.write("                <table border = \"1\" >\r\n");
      out.write("                    <thead class=\"table-primary\" >\r\n");
      out.write("                        <tr>\r\n");
      out.write("                        <td>ID</td>\r\n");
      out.write("                        <td>DeptStatus</td>\r\n");
      out.write("                        <td>ArvStatus</td>\r\n");
      out.write("                        <td>UpdateTime</td>\r\n");
      out.write("                        <td>Engineer_ID</td>\r\n");
      out.write("                        <td>TrainCode_ID</td>\r\n");
      out.write("                        <td>Train_ID</td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                    </thead>\r\n");
      out.write("                    ");

                    while(result.next()) {
                    
      out.write("\r\n");
      out.write("                    <tbody>\r\n");
      out.write("                        <tr onclick=\"trClick(this)\">\r\n");
      out.write("                        	<td>");
      out.print(result.getInt("ID"));
      out.write("</td>\r\n");
      out.write("                            <td>");
      out.print(result.getString("DeptStatus"));
      out.write("</td>\r\n");
      out.write("                            <td>");
      out.print(result.getString("ArvStatus"));
      out.write("</td>\r\n");
      out.write("                            <td>");
      out.print(result.getString("UpdateTime"));
      out.write("</td>\r\n");
      out.write("                            <td>");
      out.print(result.getString("Engineer_ID"));
      out.write("</td>\r\n");
      out.write("                            <td>");
      out.print(result.getInt("TrainCode_ID") );
      out.write("</td>\r\n");
      out.write("                            <td>");
      out.print(result.getInt("Train_ID") );
      out.write("</td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                   \r\n");
      out.write("                    </tbody>\r\n");
      out.write("                    ");
} query = "SELECT * FROM Traincode";
					result = stmt.executeQuery(query);
					
      out.write("\r\n");
      out.write("                <table border = \"1\">\r\n");
      out.write("                <h2> TrainCode table</h2>\r\n");
      out.write("                    <thead>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                        <td>ID</td>\r\n");
      out.write("                        <td>Code</td>\r\n");
      out.write("                        <td>Day</td>\r\n");
      out.write("                        <td>StartStation</td>\r\n");
      out.write("                        <td>StartTime</td>\r\n");
      out.write("                        <td>EndStation</td>\r\n");
      out.write("                        <td>EndTime</td>\r\n");
      out.write("                        <td>Line_ID</td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                    </thead>");

                    while(result.next()) {
                    
      out.write("\r\n");
      out.write("                    <tbody>\r\n");
      out.write("                        <tr onclick=\"trClick(this)\">\r\n");
      out.write("                        	<td>");
      out.print(result.getInt("ID"));
      out.write("</td>\r\n");
      out.write("                            <td>");
      out.print(result.getString("Code"));
      out.write("</td>\r\n");
      out.write("                            <td>");
      out.print(result.getString("Day"));
      out.write("</td>\r\n");
      out.write("                            <td>");
      out.print(result.getString("StartStation"));
      out.write("</td>\r\n");
      out.write("                            <td>");
      out.print(result.getString("StartTime"));
      out.write("</td>\r\n");
      out.write("                            <td>");
      out.print(result.getString("EndStation"));
      out.write("</td>\r\n");
      out.write("                            <td>");
      out.print(result.getString("EndTime"));
      out.write("</td>\r\n");
      out.write("                            <td>");
      out.print(result.getInt("Line_ID"));
      out.write("</td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                   \r\n");
      out.write("                    </tbody>\r\n");
      out.write("                    ");
}
                    query = "SELECT * FROM Train";
					result = stmt.executeQuery(query);
					
      out.write("\r\n");
      out.write("                <table border = \"1\">\r\n");
      out.write("                <h2> Train table</h2>\r\n");
      out.write("                    <thead>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                        <td>ID</td>\r\n");
      out.write("                        <td>Type</td>\r\n");
      out.write("                        <td>Conditions</td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                    </thead>");

                    while(result.next()) {
                    
      out.write("\r\n");
      out.write("                    <tbody>\r\n");
      out.write("                        <tr onclick=\"trClick(this)\">\r\n");
      out.write("                        	<td>");
      out.print(result.getInt("ID"));
      out.write("</td>\r\n");
      out.write("                            <td>");
      out.print(result.getString("Type"));
      out.write("</td>\r\n");
      out.write("                            <td>");
      out.print(result.getString("Conditions"));
      out.write("</td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                    </tbody>\r\n");
      out.write("                    ");
} 
					result = stmt.executeQuery(query2);
					
      out.write("\r\n");
      out.write("                <table border = \"1\">\r\n");
      out.write("                <h2>");
      out.print(user_name);
      out.write("기관사님 운행 정보입니다.</h2>\r\n");
      out.write("                    <thead>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                        <td>DeptStatus</td>\r\n");
      out.write("                        <td>ArvStatus</td>\r\n");
      out.write("                        <td>StartStation</td>\r\n");
      out.write("                        <td>StartTime</td>\r\n");
      out.write("                        <td>EndStation</td>\r\n");
      out.write("                        <td>EndTime</td>\r\n");
      out.write("                        <td>Type</td>\r\n");
      out.write("                        <td>Conditions</td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                    </thead>");

                    while(result.next()) {
                    
      out.write("\r\n");
      out.write("                    <tbody>\r\n");
      out.write("                        <tr onclick=\"trClick(this)\">\r\n");
      out.write("                        	<td>");
      out.print(result.getString("A.DeptStatus"));
      out.write("</td>\r\n");
      out.write("                            <td>");
      out.print(result.getString("A.ArvStatus"));
      out.write("</td>\r\n");
      out.write("                            <td>");
      out.print(result.getString("B.StartStation"));
      out.write("</td>\r\n");
      out.write("                            <td>");
      out.print(result.getString("B.StartTime"));
      out.write("</td>\r\n");
      out.write("                            <td>");
      out.print(result.getString("B.EndStation"));
      out.write("</td>\r\n");
      out.write("                            <td>");
      out.print(result.getString("B.EndTime"));
      out.write("</td>\r\n");
      out.write("                            <td>");
      out.print(result.getString("C.Type"));
      out.write("</td>\r\n");
      out.write("                            <td>");
      out.print(result.getString("C.Conditions"));
      out.write("</td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                    </tbody>");
} 
                    
					
      out.write("\r\n");
      out.write("                </table>\r\n");
      out.write("        </div>\r\n");
      out.write("        <form action =\"master_engineer_manage.jsp\" method=\"get\" style=\"width:300px; float:left;\">\r\n");
      out.write("        <h4>Insert</h4>\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("      <select name=\"DeptStatus\">\r\n");
      out.write("        <option>준비중</option>\r\n");
      out.write("        <option>정시출발</option>\r\n");
      out.write("        <option>지연출발</option>\r\n");
      out.write("      </select>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("      <select name=\"ArvStatus\">\r\n");
      out.write("        <option>출발전</option>\r\n");
      out.write("        <option>운행중</option>\r\n");
      out.write("        <option>정시도착</option>\r\n");
      out.write("        <option>지연도착</option>\r\n");
      out.write("      </select>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("        <input name=\"UpdateTime\" type=\"text\" placeHolder=\"UpdateTime\">\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("        <input name=\"Engineer_ID\" type=\"hidden\" value=\"");
      out.print(Engineer_ID);
      out.write("\">\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("        <input name=\"TrainCode_ID\" type=\"text\" placeHolder=\"TrainCode_ID\">\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("        <input name=\"Train_ID\" type=\"text\" placeHolder=\"Train_ID\">\r\n");
      out.write("        </div>\r\n");
      out.write("        <div>\r\n");
      out.write("        <button id=\"insert_button1\" type = \"submit\" style=\"background-color: #4c59fd\">insert</button>\r\n");
      out.write("        </div>\r\n");
      out.write("        <input name=\"manage_num\" type=\"hidden\" value=\"1\">\r\n");
      out.write("        </form>\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("          \r\n");
      out.write("        <form action=\"master_engineer_manage.jsp\" method=\"get\"style=\"width:300px; float:left;\">\r\n");
      out.write("         <h4>Update</h4>\r\n");
      out.write("        <p>update할 아이디를 입력하세요!</p>\r\n");
      out.write("       <div class=\"row\">\r\n");
      out.write("        <input name=\"masterupdate_id\" type=\"text\" placeHolder=\"id\">\r\n");
      out.write("        </div>\r\n");
      out.write("       <div class=\"row\">\r\n");
      out.write("      <select name=\"select\">\r\n");
      out.write("        <option>DeptStatus</option>\r\n");
      out.write("        <option>ArvStatus</option>\r\n");
      out.write("        <option>UpdateTime</option>\r\n");
      out.write("        <option>Engineer_ID</option>\r\n");
      out.write("        <option>TrainCode_ID	</option>\r\n");
      out.write("        <option>Train_ID</option>\r\n");
      out.write("      </select>\r\n");
      out.write("        </div>\r\n");
      out.write("       <div class=\"row\">\r\n");
      out.write("        <input name=\"update\" type=\"text\" placeHolder=\"수정값\">\r\n");
      out.write("        </div>\r\n");
      out.write("        <div>\r\n");
      out.write("        <button type = \"submit\" style=\"background-color: #4c59fd\">update</button>\r\n");
      out.write("        </div>\r\n");
      out.write("        <input name=\"manage_num\" type=\"hidden\" value=\"2\">\r\n");
      out.write("        </form>\r\n");
      out.write("        \r\n");
      out.write("        <form action=\"master_engineer_manage.jsp\" method=\"get\" style=\"width:300px; float:left;\">\r\n");
      out.write("        <h4>Delete</h4>\r\n");
      out.write("        <p>delete할 아이디를 입력하세요!</p>\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("        <input name=\"masterdelete_id\" type=\"text\" placeHolder=\"id\">\r\n");
      out.write("        </div>\r\n");
      out.write("        <div>\r\n");
      out.write("        <button type = \"submit\" style=\"background-color: #4c59fd\">delete</button>\r\n");
      out.write("        </div>\r\n");
      out.write("        <input name=\"manage_num\" type=\"hidden\" value=\"3\">\r\n");
      out.write("        </form>\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("     <iframe src=\"operation_status.jsp\" width=\"100%\" height=\"500\" frameborder=\"1\"></frame>\r\n");
      out.write("  \r\n");
      out.write("    </div>\r\n");
      out.write("         </div>\r\n");
      out.write("    \r\n");

	result.close();
	stmt.close();
	conn.close();
} catch(SQLException e) {
	out.println("err."+e.toString());
}
	
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
